# test-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"

# python-unit-tests:
#   image: python:3.6
#   stage: test
#   script:
#     - pip install -r backend/requirements.txt
#     - make python-unit-tests

selenium-tests:
  image: python:3.6
  stage: test
  script:
    - pip install selenium
    - npm install chromedriver
    - make selenium-tests

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."