cuisines = [
    {
        "id": 1,
        "name": "Cuisine 1",
        "country": "Country 1",
        "dishes": [
            {
                "name": "Dish 1",
                "image_url": "Dish_1.jpg"
            },
        ],
        "description": "Cuisine 1 description",
        "countryID": "1",
        "restaurant_ids": "1",
        "city_ids": "1",
        "restaurants": "Restaurant 1",
        "cities": "City 1"
    },
    {
        "id": 2,
        "name": "Cuisine 2",
        "country": "Country 2",
        "dishes": [
            {
                "name": "Dish 2",
                "image_url": "Dish_2.jpg"
            },
        ],
        "description": "Cuisine 2 description",
        "countryID": "2",
        "restaurant_ids": "2",
        "city_ids": "2",
        "restaurants": "Restaurant 2",
        "cities": "City 2"
    },
    {
        "id": 3,
        "name": "Cuisine 3",
        "country": "Country 3",
        "dishes": [
            {
                "name": "Dish 3",
                "image_url": "Dish_3.jpg"
            },
        ],
        "description": "Cuisine 3 description",
        "countryID": "3",
        "restaurant_ids": "3",
        "city_ids": "3",
        "restaurants": "Restaurant 3",
        "cities": "City 3"
    },

]

countries = [
    {
        "id": 1,
        "name": "Country 1",
        "alpha2code": "C1",
        "alpha3code": "CO1",
        "capital": "Capital 1",
        "region": "Region 1",
        "subregion": "Subregion 1",
        "population": 500,
        "latitude": 0.0,
        "longitude": 0.0,
        "demonym": "Country 1",
        "area": 100.0,
        "gini": 10.0,
        "timezones": "UTC+00:00",
        "borders": "CO2, CO3",
        "native_name": "Country 1",
        "numeric_code": 1,
        "currencies": "C01",
        "languages": "CO1",
        "translations": {
            "de": "CO1",
            "es": "CO1",
            "fr": "CO1",
            "ja": "CO1",
            "it": "CO1",
            "br": "CO1",
            "pt": "CO1",
            "nl": "CO1",
            "hr": "CO1",
            "fa": "CO1"
        },
        "flag": "CO1.svg"
    },
    {
        "id": 2,
        "name": "Country 2",
        "alpha2code": "C2",
        "alpha3code": "CO2",
        "capital": "Capital 2",
        "region": "Region 2",
        "subregion": "Subregion 2",
        "population": 1000,
        "latitude": 1.0,
        "longitude": 1.0,
        "demonym": "Country 2",
        "area": 200.0,
        "gini": 20.0,
        "timezones": "UTC+01:00",
        "borders": "CO1, CO3",
        "native_name": "Country 2",
        "numeric_code": 2,
        "currencies": "C02",
        "languages": "CO2",
        "translations": {
            "de": "CO2",
            "es": "CO2",
            "fr": "CO2",
            "ja": "CO2",
            "it": "CO2",
            "br": "CO2",
            "pt": "CO2",
            "nl": "CO2",
            "hr": "CO2",
            "fa": "CO2"
        },
        "flag": "CO2.svg"
    },
    {
        "id": 3,
        "name": "Country 3",
        "alpha2code": "C3",
        "alpha3code": "CO3",
        "capital": "Capital 3",
        "region": "Region 3",
        "subregion": "Subregion 3",
        "population": 1500,
        "latitude": 2.0,
        "longitude": 2.0,
        "demonym": "Country 3",
        "area": 300.0,
        "gini": 30.0,
        "timezones": "UTC+02:00",
        "borders": "CO1, CO2",
        "native_name": "Country 3",
        "numeric_code": 3,
        "currencies": "C03",
        "languages": "CO3",
        "translations": {
            "de": "CO3",
            "es": "CO3",
            "fr": "CO3",
            "ja": "CO3",
            "it": "CO3",
            "br": "CO3",
            "pt": "CO3",
            "nl": "CO3",
            "hr": "CO3",
            "fa": "CO3"
        },
        "flag": "CO3.svg"
    }
]

cities = [
    {
        "id": 1,
        "name": "City 1",
        "full_name": "City 1, State 1, Country 1",
        "population": 100,
        "latitude": 10,
        "longitude": -10,
        "state": "State 1",
        "timezone": "Country_1/City_1",
        "imagesmobile": "city_1_mobile.jpg",
        "imagesweb": "city_1_web.jpg",
        "housing": 8.0,
        "cost_of_living": 8.0,
        "startups": 8.0,
        "venture_capital": 8.0,
        "travel_connectivity": 8.0,
        "commute": 8.0,
        "business_freedom": 8.0,
        "safety": 8.0,
        "healthcare": 8.0,
        "education": 8.0,
        "environmental_quality": 8.0,
        "economy": 8.0,
        "taxation": 8.0,
        "internet_access": 8.0,
        "leisure_culture": 8.0,
        "tolerance": 8.0,
        "outdoors": 8.0,
        "summary": "City 1 description",
        "cuisine_ids": "1",
        "restaurant_ids": "1",
        "cuisines": "Cuisine 1",
        "restaurants": "Restaurant 1"
    },
    {
        "id": 2,
        "name": "City 2",
        "full_name": "City 2, State 2, Country 2",
        "population": 200,
        "latitude": 20,
        "longitude": -20,
        "state": "State 2",
        "timezone": "Country_2/City_2",
        "imagesmobile": "city_2_mobile.jpg",
        "imagesweb": "city_2_web.jpg",
        "housing": 9.0,
        "cost_of_living": 9.0,
        "startups": 9.0,
        "venture_capital": 9.0,
        "travel_connectivity": 9.0,
        "commute": 9.0,
        "business_freedom": 9.0,
        "safety": 9.0,
        "healthcare": 9.0,
        "education": 9.0,
        "environmental_quality": 9.0,
        "economy": 9.0,
        "taxation": 9.0,
        "internet_access": 9.0,
        "leisure_culture": 9.0,
        "tolerance": 9.0,
        "outdoors": 9.0,
        "summary": "City 2 description",
        "cuisine_ids": "2",
        "restaurant_ids": "2",
        "cuisines": "Cuisine 2",
        "restaurants": "Restaurant 2"
    },
    {
        "id": 3,
        "name": "City 3",
        "full_name": "City 3, State 3, Country 3",
        "population": 300,
        "latitude": 30,
        "longitude": -30,
        "state": "State 3",
        "timezone": "Country_3/City_3",
        "imagesmobile": "city_3_mobile.jpg",
        "imagesweb": "city_3_web.jpg",
        "housing": 10.0,
        "cost_of_living": 10.0,
        "startups": 10.0,
        "venture_capital": 10.0,
        "travel_connectivity": 10.0,
        "commute": 10.0,
        "business_freedom": 10.0,
        "safety": 10.0,
        "healthcare": 10.0,
        "education": 10.0,
        "environmental_quality": 10.0,
        "economy": 10.0,
        "taxation": 10.0,
        "internet_access": 10.0,
        "leisure_culture": 10.0,
        "tolerance": 10.0,
        "outdoors": 10.0,
        "summary": "City 3 description",
        "cuisine_ids": "3",
        "restaurant_ids": "3",
        "cuisines": "Cuisine 3",
        "restaurants": "Restaurant 3"
    }
]

restaurants = [
    {
        "id": 1,
        "aggregate_rating": "8.0",
        "average_cost_for_two": 10,
        "cuisines": "Cuisine 1",
        "highlights": "Highlight 1",
        "menu_url": "menu_1.jpg",
        "name": "Restaurant 1",
        "phone_numbers": "(111) 111-1111",
        "price_range": 1,
        "restaurant_image": "restaurant_1.jpg",
        "timings": "10:30 AM to 9 PM (Mon-Thu), 10:30 AM to 10 PM (Fri-Sat), 11 AM to 9 PM (Sun)",
        "url": "restaurant_1.com",
        "address": "Address 1",
        "city": "City 1",
        "latitude": "10.0",
        "longitude": "-10.0",
        "state_abbrev": "S1",
        "zipcode": "11111",
        "cuisine_ids": "1",
        "city_id": 1
    },
    {
        "id": 2,
        "aggregate_rating": "9.0",
        "average_cost_for_two": 20,
        "cuisines": "Cuisine 2",
        "highlights": "Highlight 2",
        "menu_url": "menu_2.jpg",
        "name": "Restaurant 2",
        "phone_numbers": "(222) 222-2222",
        "price_range": 2,
        "restaurant_image": "restaurant_2jpg",
        "timings": "10:30 AM to 9 PM (Mon-Thu), 10:30 AM to 10 PM (Fri-Sat), 11 AM to 9 PM (Sun)",
        "url": "restaurant_2.com",
        "address": "Address 2",
        "city": "City 2",
        "latitude": "20.0",
        "longitude": "-20.0",
        "state_abbrev": "S2",
        "zipcode": "22222",
        "cuisine_ids": "2",
        "city_id": 2
    },
    {
        "id": 3,
        "aggregate_rating": "10.0",
        "average_cost_for_two": 30,
        "cuisines": "Cuisine 3",
        "highlights": "Highlight 3",
        "menu_url": "menu_3.jpg",
        "name": "Restaurant 3",
        "phone_numbers": "(333) 333-3333",
        "price_range": 3,
        "restaurant_image": "restaurant_3.jpg",
        "timings": "10:30 AM to 9 PM (Mon-Thu), 10:30 AM to 10 PM (Fri-Sat), 11 AM to 9 PM (Sun)",
        "url": "restaurant_3.com",
        "address": "Address 3",
        "city": "City 3",
        "latitude": "30.0",
        "longitude": "-30.0",
        "state_abbrev": "S3",
        "zipcode": "33333",
        "cuisine_ids": "3",
        "city_id": 3
    }
]
